inherit_from: .rubocop_todo.yml

inherit_gem:
  betterlint:
    - config/default.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'gemfiles/*.gemfile'
    - 'lib/generators/delayed/templates/*.rb'
  NewCops: enable

Rails/EnvironmentVariableAccess:
  Enabled: false

RSpec/IndexedLet:
  Enabled: false

Capybara/RSpec/PredicateMatcher:
  Enabled: false
