Metrics/AbcSize:
  Enabled: false

Metrics/BlockNesting:
  Max: 2

Metrics/LineLength:
  AllowURI: true
  Enabled: false

Metrics/MethodLength:
  CountComments: false
  Max: 47 # TODO: Lower to 15

Metrics/ModuleLength:
  Max: 150 # TODO: Lower to 100

Metrics/ParameterLists:
  Max: 4
  CountKeywordArgs: true

Style/AccessModifierIndentation:
  EnforcedStyle: outdent

Style/CollectionMethods:
  PreferredMethods:
    map:      'collect'
    reduce:   'inject'
    find:     'detect'
    find_all: 'select'

Style/Documentation:
  Enabled: false

Style/DotPosition:
  EnforcedStyle: trailing

Style/DoubleNegation:
  Enabled: false

Style/EachWithObject:
  Enabled: false

Style/Encoding:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/Lambda:
  Enabled: false

Style/RaiseArgs:
  EnforcedStyle: compact

Style/RegexpLiteral:
  Exclude:
    - lib/delayed/psych_ext.rb

Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/StructInheritance:
  Enabled: false

Style/TrailingComma:
  EnforcedStyleForMultiline: 'comma'
