mysql:
  adapter: mysql
  host: 127.0.0.1
  database: delayed_job_test
  username: root
  port: 3306
  encoding: utf8

mysql2:
  adapter: mysql2
  host: 127.0.0.1
  database: delayed_job_test
  username: root
  port: 3306
  encoding: utf8

postgresql:
  adapter: postgresql
  host: 127.0.0.1
  url: <%= ENV.fetch('DATABASE_URL', 'postgresql://127.0.0.1/delayed_job_test') %>
  password: postgres

sqlite3:
  adapter: sqlite3
  database: "tmp/database.sqlite"
